### PR TITLE
Update nl.coffee

### PR DESCRIPTION
**Pull request by PolyglotOpenstreetmap**
compared to version of Sander and replaced where his strings were better.

### CODE REVIEW

**Comment by knikel** [comment]
Thanks a lot @PolyglotOpenstreetmap, you rock! :metal:

**Comment by PolyglotOpenstreetmap** [comment]
You're welcome. When will it show up on the website?

Jo

**Comment by knikel** [comment]
@PolyglotOpenstreetmap The translation is out now.

**Comment by PolyglotOpenstreetmap** [comment]
Oddly this is still in English:

Log in
E-mail
Password
Sign up
Forgot your password

Jo

2015-02-21 23:29 GMT+01:00 Kamil Nikel <notifications@github.com>:

**Pull request merged**
