### PR TITLE
Ukrainian translation

### PR DESCRIPTION
**Pull request by Andygol**

### CODE REVIEW

**Comment by knikel** [comment]
Дякую @Andygol! :+1:

**Comment by Andygol** [comment]
@knikel I have just checked Ukrainian localization
image
 
It seems that I'm not all translated or need something to fix

I need your help/advice about it.

**Comment by older** [comment]
@Andygol - it is good to see Ukrainian translation. I have a question though. You use word `застосунок` for `application` as used by Microsoft, but Google in Play market translate `app` as `додаток` which makes it confusing a little for people who have never used Ukrainian interface with Microsoft products. Is it possible to make it use something like `застосунки та додатки` somewhere?

Also some proofreading:
* автіки -> автівки
* Інтергруйте -> Інтегруйте
* меную -> меню

**Comment by Andygol** [comment]
@older thanks for proofreading

**Pull request merged**
